cabal-version: 2.4
name:          kafka
version:       0.2
license:       BSD-3-Clause
license-file:  LICENSE
author:        Ethan Jones, Jose Cardona
build-type:    Simple
extra-source-files: CHANGELOG.md

library
  exposed-modules:
    Kafka.Client
    Kafka.Common
    Kafka.Consumer
    Kafka.Consumer.New
    Kafka.Consumer.Types
    Kafka.Producer
    Kafka.Producer.Types

    Kafka.Internal.ApiVersions.Request
    Kafka.Internal.ApiVersions.Response
    Kafka.Internal.Broker
    Kafka.Internal.Combinator
    Kafka.Internal.Compression
    Kafka.Internal.Config
    Kafka.Internal.FindCoordinator.Request
    Kafka.Internal.FindCoordinator.Response
    Kafka.Internal.Fetch.Request
    Kafka.Internal.Fetch.Response
    Kafka.Internal.Heartbeat.Request
    Kafka.Internal.InitProducerId.Request
    Kafka.Internal.InitProducerId.Response
    Kafka.Internal.Heartbeat.Response
    Kafka.Internal.JoinGroup.Request
    Kafka.Internal.JoinGroup.Response
    Kafka.Internal.LeaveGroup.Request
    Kafka.Internal.LeaveGroup.Response
    Kafka.Internal.ListOffsets.Request
    Kafka.Internal.ListOffsets.Response
    Kafka.Internal.Metadata.Request
    Kafka.Internal.Metadata.Response
    Kafka.Internal.Murmur2
    Kafka.Internal.OffsetCommit.Request
    Kafka.Internal.OffsetCommit.Response
    Kafka.Internal.OffsetFetch.Request
    Kafka.Internal.OffsetFetch.Response
    Kafka.Internal.Produce.Request
    Kafka.Internal.Produce.Response
    Kafka.Internal.RecordBatch
    Kafka.Internal.Reconnect
    Kafka.Internal.Request
    Kafka.Internal.Request.Types
    Kafka.Internal.Response
    Kafka.Internal.ShowDebug
    Kafka.Internal.SyncGroup.Request
    Kafka.Internal.SyncGroup.Response
    Kafka.Internal.Topic
    Kafka.Internal.Wire
    Kafka.Internal.Writer
    Kafka.Internal.Zigzag
  -- Prelude: using base's standard Prelude
  ghc-options:
    -Wall
    -O2
  build-depends:
    , async             >= 2.2
    , base              >= 4.16
    , byteslice         >= 0.2
    , bytesmith         >= 0.3
    , bytestring        >= 0.11
    , containers        >= 0.6
    , digest            >= 0.0.2
    , contiguous        >= 0.5
    , mtl               >= 2.2
    , network           >= 3.1
    , primitive          >= 0.9
    , primitive-unlifted >= 0.1
    , proto3-wire       >= 1.4
    , stm               >= 2.5
    , transformers      >= 0.5
    , lz4               >= 0.2
    , snappy            >= 0.2
    , zlib              >= 0.6
    , zstd              >= 0.1
  hs-source-dirs:
    src
  default-language:
    GHC2024

test-suite unit
  type:             exitcode-stdio-1.0
  main-is:          UnitTests.hs
  other-modules:    WireTests
  hs-source-dirs:   test
  build-depends:
    , base
    , bytesmith
    , byteslice
    , bytestring
    , containers
    , kafka
    , primitive
    , primitive-unlifted
    , tasty
    , tasty-golden
    , tasty-hunit
  default-language: GHC2024
  ghc-options:      -Wall -O2

test-suite integration
  type:             exitcode-stdio-1.0
  main-is:          IntegrationTests.hs
  other-modules:    MockCluster
  hs-source-dirs:   test
  build-depends:
    , async
    , base
    , bytestring
    , kafka
    , network
    , primitive
    , stm
    , tasty
    , tasty-hunit
  extra-libraries:  rdkafka
  if os(darwin)
    extra-lib-dirs:   /opt/homebrew/lib
    include-dirs:     /opt/homebrew/include
  if os(linux)
    extra-lib-dirs:   /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/aarch64-linux-gnu
    include-dirs:     /usr/include /usr/include/librdkafka
  default-language: GHC2024
  ghc-options:      -Wall -O2 -threaded

benchmark wire-parse
  type:             exitcode-stdio-1.0
  main-is:          WireBench.hs
  hs-source-dirs:   bench
  build-depends:
    , base
    , bytesmith
    , byteslice
    , bytestring
    , criterion
    , deepseq
    , kafka
    , primitive
  default-language: GHC2024
  ghc-options:      -Wall -O2

benchmark throughput
  type:             exitcode-stdio-1.0
  main-is:          Benchmark.hs
  other-modules:    MockCluster
  hs-source-dirs:   bench test
  build-depends:
    , base
    , bytestring
    , criterion
    , deepseq
    , hw-kafka-client
    , kafka
    , network
    , primitive
    , stm
    , text
  extra-libraries:  rdkafka
  if os(darwin)
    extra-lib-dirs:   /opt/homebrew/lib
    include-dirs:     /opt/homebrew/include
  if os(linux)
    extra-lib-dirs:   /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/aarch64-linux-gnu
    include-dirs:     /usr/include /usr/include/librdkafka
  default-language: GHC2024
  ghc-options:      -Wall -O2 -threaded -rtsopts "-with-rtsopts=-N"
